on:
  workflow_call:
    inputs:
      jar_name:
        required: true
        type: string
      paths:
        required: true
        type: string
      stage:
        required: false
        default: development
        type: string
    secrets:
      conn_ip:
        required: true
      conn_user:
        required: true
      ssh_key:
        required: true
      gh_token:
        required: false
jobs:
  deploy:
    runs-on: self-hosted
    env:
      JAR: ${{ inputs.jar_name }}
      PATHS: ${{ inputs.paths }}
      STAGE: ${{ inputs.stage }}
      IP: ${{ secrets.conn_ip }}
      USER: ${{ secrets.conn_user }}
      GH_TOKEN: ${{ secrets.gh_token }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: "8.1.1"

      - name: Build with Gradle
        run: gradle shadowJar

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ssh_key }}

      - name: Setup SSH known_hosts
        run: ssh-keyscan $IP >> ~/.ssh/known_hosts

      - name: Copy file to Academy
        shell: bash
        run: |
          for path in $(echo $PATHS | tr ", " " "); do 
            scp build/libs/$JAR $USER@$IP:~/$STAGE/servers/$path/plugins/update/$JAR
          done
